### ISSUE TITLE
Comandos servidores

### ISSUE THREAD

**Issue by PokeToribio** [ThePotatoCamera/DiscordGamers-Bot#2]
Un comando para que ponga link de invitacion a todos los servidores de DG 

Ejemplo: <servidoresdg

Pokemon: (link de invitacion)

PlayStation: (link de invitacion)

etz

**Comment by ThePotatoCamera** [comment]
Se añadirá a la versión 1.1.0

**Comment by ThePotatoCamera** [comment]
Ya disponible en **Canary** [https://github.com/ThePotatoCamera/DiscordGamers-Bot/tree/Canary](url)
