### ISSUE TITLE
Añadir comandos de entretenimiento.

### ISSUE THREAD

**Issue by ThePotatoCamera** [ThePotatoCamera/DiscordGamers-Bot#7]
(Pedido por **MarisaTheKiller#1852**)

Ideas de comandos de entretenimiento.

Idea | ¿Lista?
----------|----------
Dados | [ x ]
Bola 8 | [ x ]

**Comment by Enrique23f** [comment]
Si pones <dog que hayan fotitos de perros y perritos

**Comment by ThePotatoCamera** [comment]
> 
> 
> Si pones <dog que hayan fotitos de perros y perritos

Requiere un aleatorizador de imagenes, cosa muy compleja :/
